### ISSUE TITLE
crashes on webstorm: Icon cannot be found in 'GithubIcons.Github_icon'

### ISSUE THREAD

**Issue by iolo** [shiraji/open-commit-on-github#6]
## Stacktrace

```
com.intellij.diagnostic.PluginException: Icon cannot be found in 'GithubIcons.Github_icon', action 'class com.github.shiraji.opencommitongithub.actions.OpenCommitOnGitHubAction' [Plugin: com.github.shiraji.opencommitongithub]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:390)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionError(ActionManagerImpl.java:385)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.setIconFromClass(ActionManagerImpl.java:302)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.updateIconFromStub(ActionManagerImpl.java:267)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:227)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:570)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1621)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:15)
	at com.intellij.openapi.application.Preloader.lambda$preload$0(Preloader.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.application.Preloader.lambda$preload$1(Preloader.java:74)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

## environment

```
WebStorm 2020.3
Build #WS-203.5981.135, November 28, 2020
Licensed to Dongsu Jang
Subscription is active until November 3, 2021
Runtime Version: 11.0.9+11-b1145.21 x86_64
VM: JetBrains s.r.o.의 OpenJDK 64-Bit Server VM
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: debugger.watches.in.variables=false, ide.balloon.shadow.size=0, js.debugger.webconsole=false
Non-Bundled Plugins: IdeaVIM, com.andrey4623.rainbowcsv, com.intellij.ko, com.jetbrains.darkPurpleTheme, com.jonathonstaff.ideaascii, com.vexus2.intellij.openingithub, indent-rainbow.indent-rainbow, com.github.shiraji.opencommitongithub, com.jetbrains.codeWithMe, org.zalando.intellij.swagger, com.intellij.database, izhangzhihao.rainbow.brackets, ru.adelf.idea.dotenv
```

Thanks

**Comment by shiraji** [comment]
Thanks for reporting

**Comment by gnutix** [comment]
Same for me : 

```
PhpStorm 2021.1
Build #PS-211.6693.120, built on April 7, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-7612-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: awesome.console (0.1337.11), com.andrewbrookins.wrap_to_column (1.4.0), de.netnexus.camelcaseplugin (3.0.8), one.util.ideaplugin.screenshoter (1.5), com.github.shiraji.opencommitongithub (1.0.2), name.kropp.intellij.makefile (3.5.2), MetricsReloaded (1.11.2), com.kalessil.phpStorm.phpInspectionsEA (4.0.6.3), com.phpuaca (1.3.5), de.espend.idea.php.toolbox (5.1.1), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.22.206), ru.adelf.idea.dotenv (2021.1)
Current Desktop: X-Cinnamon
```

**Comment by yonifra** [comment]
happens for me as well (WebStorm)
I guess it's an easy fix, just a resource that needs to be added. @shiraji
